# Generated by Django 5.2.5 on 2025-10-29 08:36

import agent.utils
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('persona', models.TextField(blank=True, max_length=500)),
                ('max_tokens', models.IntegerField(default=300)),
                ('glb_url', models.URLField(blank=True, max_length=500, null=True)),
                ('avatar', models.ImageField(blank=True, max_length=250, null=True, upload_to=agent.utils.agent_upload_path)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('service', models.CharField(choices=[('gtts', 'gTTS'), ('elevenlabs', 'ElevenLabs'), ('openai', 'OpenAI'), ('google', 'Google')], default='gtts', help_text='TTS provider (e.g., gtts, elevenlabs).', max_length=150)),
                ('voice_id', models.CharField(choices=[('gTTS', [('gtts::ar@com.sa', 'Arabic (Saudi)'), ('gtts::zh-cn@com.hk', 'Chinese (Mandarin)'), ('gtts::en@com.au', 'English (AU)'), ('gtts::en@co.in', 'English (India)'), ('gtts::en@ie', 'English (Ireland)'), ('gtts::en@co.za', 'English (South Africa)'), ('gtts::en@co.uk', 'English (UK)'), ('gtts::en@com', 'English (US)'), ('gtts::fr@fr', 'French (France)'), ('gtts::de@de', 'German (Germany)'), ('gtts::hi@co.in', 'Hindi (India)'), ('gtts::it@it', 'Italian (Italy)'), ('gtts::ja@co.jp', 'Japanese (Japan)'), ('gtts::ko@co.kr', 'Korean (Korea)'), ('gtts::pt@com.br', 'Portuguese (Brazil)'), ('gtts::es@com', 'Spanish (Global)'), ('gtts::es@com.mx', 'Spanish (Mexico)')]), ('ElevenLabs', [('elevenlabs::Xb7hH8MSUJpSbSDYk0k2', 'Alice'), ('elevenlabs::9BWtsMINqrJLrRacOk9x', 'Aria'), ('elevenlabs::pqHfZKP75CvOlQylNhV4', 'Bill'), ('elevenlabs::nPczCjzI2devNBz1zQrb', 'Brian'), ('elevenlabs::N2lVS1w4EtoT3dr4eOWO', 'Callum'), ('elevenlabs::IKne3meq5aSn9XLyUdCD', 'Charlie'), ('elevenlabs::XB0fDUnXU5powFXDhCwa', 'Charlotte'), ('elevenlabs::onwK4e9ZLuTAKqWW03F9', 'Daniel'), ('elevenlabs::TxGEqnHWrfWFTfGW9XjX', 'Elli'), ('elevenlabs::cjVigY5qzO86Huf0OWal', 'Eric'), ('elevenlabs::JBFqnCBsd6RMkjVDRZzb', 'George'), ('elevenlabs::cgSgspJ2msm6clMCkdW9', 'Jessica'), ('elevenlabs::FGY2WhTYpPnrIDTdsKH5', 'Laura'), ('elevenlabs::TX3LPaxmHKxFdv7VOQHJ', 'Liam'), ('elevenlabs::XrExE9yKIg1WjnnlVkGX', 'Matilda'), ('elevenlabs::21m00Tcm4TlvDq8ikWAM', 'Rachel'), ('elevenlabs::SAz9YHcvj6GT2YYXdXww', 'River'), ('elevenlabs::pMsXgVXv3BLzUgSXRplE', 'Sam'), ('elevenlabs::EXAVITQu4vr4xnSDxMaL', 'Sarah'), ('elevenlabs::bIHbv24MWmeRgasZH58o', 'Will')])], default='gtts::en@com', help_text='Voice ID with service prefix (e.g., gtts::en@com, openai::alloy).', max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', help_text='Voice gender.', max_length=150)),
                ('preview', models.FileField(blank=True, max_length=250, null=True, upload_to=agent.utils.voice_upload_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Voice',
                'verbose_name_plural': 'Voices',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
