# Generated by Django 5.2.5 on 2025-10-29 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='voice',
            index=models.Index(fields=['service', 'gender'], name='agent_voice_service_c329d6_idx'),
        ),
        migrations.AddField(
            model_name='agent',
            name='voice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='agent.voice'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['user', 'is_active'], name='agent_agent_user_id_2d2e92_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['created_at'], name='agent_agent_created_2227df_idx'),
        ),
    ]
