# Generated by Django 5.2.5 on 2025-11-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='service',
            field=models.CharField(choices=[('gtts', 'gTTS'), ('elevenlabs', 'ElevenLabs'), ('openai', 'OpenAI')], default='gtts', help_text='TTS provider (e.g., gtts, elevenlabs).', max_length=150),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice_id',
            field=models.CharField(choices=[('gTTS', [('gtts::ar@com.sa', 'Arabic'), ('gtts::zh-cn@com.hk', 'Chinese'), ('gtts::en@com', 'English'), ('gtts::fr@fr', 'French'), ('gtts::de@de', 'German'), ('gtts::hi@co.in', 'Hindi'), ('gtts::it@it', 'Italian'), ('gtts::ja@co.jp', 'Japanese'), ('gtts::ko@co.kr', 'Korean'), ('gtts::pt@com.br', 'Portuguese'), ('gtts::es@com', 'Spanish')]), ('OpenAI', [('openai::alloy', 'Alloy'), ('openai::ash', 'Ash'), ('openai::ballad', 'Ballad'), ('openai::coral', 'Coral'), ('openai::echo', 'Echo'), ('openai::fable', 'Fable'), ('openai::nova', 'Nova'), ('openai::onyx', 'Onyx'), ('openai::sage', 'Sage'), ('openai::shimmer', 'Shimmer'), ('openai::verse', 'Verse')]), ('ElevenLabs', [('elevenlabs::Xb7hH8MSUJpSbSDYk0k2', 'Alice'), ('elevenlabs::9BWtsMINqrJLrRacOk9x', 'Aria'), ('elevenlabs::pqHfZKP75CvOlQylNhV4', 'Bill'), ('elevenlabs::nPczCjzI2devNBz1zQrb', 'Brian'), ('elevenlabs::N2lVS1w4EtoT3dr4eOWO', 'Callum'), ('elevenlabs::IKne3meq5aSn9XLyUdCD', 'Charlie'), ('elevenlabs::XB0fDUnXU5powFXDhCwa', 'Charlotte'), ('elevenlabs::onwK4e9ZLuTAKqWW03F9', 'Daniel'), ('elevenlabs::TxGEqnHWrfWFTfGW9XjX', 'Elli'), ('elevenlabs::cjVigY5qzO86Huf0OWal', 'Eric'), ('elevenlabs::JBFqnCBsd6RMkjVDRZzb', 'George'), ('elevenlabs::cgSgspJ2msm6clMCkdW9', 'Jessica'), ('elevenlabs::FGY2WhTYpPnrIDTdsKH5', 'Laura'), ('elevenlabs::TX3LPaxmHKxFdv7VOQHJ', 'Liam'), ('elevenlabs::XrExE9yKIg1WjnnlVkGX', 'Matilda'), ('elevenlabs::21m00Tcm4TlvDq8ikWAM', 'Rachel'), ('elevenlabs::SAz9YHcvj6GT2YYXdXww', 'River'), ('elevenlabs::pMsXgVXv3BLzUgSXRplE', 'Sam'), ('elevenlabs::EXAVITQu4vr4xnSDxMaL', 'Sarah'), ('elevenlabs::bIHbv24MWmeRgasZH58o', 'Will')])], default='gtts::en@com', help_text='Voice ID with service prefix (e.g., gtts::en@com, openai::alloy).', max_length=255),
        ),
    ]
