# Generated by Django 5.2.5 on 2025-11-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_voice_service_alter_voice_voice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='glb_url',
            new_name='glb',
        ),
        migrations.AddField(
            model_name='agent',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
