# Generated by Django 5.2.5 on 2025-10-29 08:36

import django.db.models.deletion
import django.utils.timezone
import memory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.TextField(help_text='User message / prompt.')),
                ('response', models.TextField(blank=True, default='', help_text='Assistant final reply text/markdown.')),
                ('emotion', models.JSONField(blank=True, default=dict, help_text='e.g. {"name":"joy","intensity":2}')),
                ('viseme', models.JSONField(blank=True, default=dict, help_text='Viseme timeline (+ optional audio ref) for this assistant response.')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Debug/runtime metadata, timings, routing info, etc.')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', help_text='Short display name for this slide deck.', max_length=255)),
                ('summary', models.TextField(blank=True, default='', help_text='Short outline / summary of the deck for fast context use.')),
                ('editorjs', models.JSONField(blank=True, default=dict, help_text='Full editor.js JSON for the current slide deck.')),
            ],
            options={
                'verbose_name': 'Slides',
                'verbose_name_plural': 'Slides',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread_id', models.CharField(db_index=True, default=memory.models.generate_thread_id, max_length=100, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='agent.agent')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
