# Generated by Django 5.2.5 on 2025-10-29 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='memory.session'),
        ),
        migrations.AddField(
            model_name='slides',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='memory.session'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'agent', 'created_at'], name='memory_sess_user_id_a5b1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['session', 'created_at'], name='memory_chat_session_953259_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['created_at'], name='memory_chat_created_3e66c4_idx'),
        ),
    ]
