# Generated by Django 5.2.5 on 2025-11-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='previous_editorjs',
            field=models.JSONField(blank=True, default=dict, help_text='Previous Editor.js JSON (single snapshot).'),
        ),
        migrations.AddField(
            model_name='slides',
            name='previous_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='slides',
            name='previous_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='slides',
            name='updated_by',
            field=models.CharField(blank=True, default='', help_text='who updated this: ai | user | tool:<name>', max_length=64),
        ),
        migrations.AddField(
            model_name='slides',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Monotonic version; increments on each update.'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='editorjs',
            field=models.JSONField(blank=True, default=dict, help_text='Editor.js JSON for the current deck.'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='slides',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
