# Generated by Django 5.2.5 on 2025-11-08 00:53

import django.db.models.deletion
import django.utils.timezone
import memory.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_voice_service_alter_voice_voice_id'),
        ('memory', '0003_slides_previous_editorjs_slides_previous_summary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slides',
            name='previous_editorjs',
        ),
        migrations.RemoveField(
            model_name='slides',
            name='previous_summary',
        ),
        migrations.RemoveField(
            model_name='slides',
            name='previous_title',
        ),
        migrations.AlterField(
            model_name='chat',
            name='viseme',
            field=models.JSONField(blank=True, default=dict, help_text='Viseme timeline (+ optional audio ref).'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Monotonic version; increments on each change.'),
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, default='', help_text='Optional human-readable title.', max_length=255)),
                ('original_name', models.CharField(help_text='Original filename at upload time.', max_length=255)),
                ('file', models.FileField(max_length=500, upload_to=memory.models.knowledge_upload_to)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('mimetype', models.CharField(blank=True, default='', max_length=100)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('ext', models.CharField(blank=True, default='', max_length=16)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('rows', models.PositiveIntegerField(blank=True, null=True)),
                ('cols', models.PositiveIntegerField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True, default='', help_text='First ~4k chars of extracted text for quick search.')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('index_status', models.CharField(choices=[('unindexed', 'Unindexed'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='unindexed', max_length=16)),
                ('index_meta', models.JSONField(blank=True, default=dict)),
                ('normalized_name', models.CharField(blank=True, db_index=True, default='', max_length=300)),
                ('search_terms', models.JSONField(blank=True, default=list, help_text='Lowercased variants, tokens, slugs, aliases.')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='agent.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge',
                'verbose_name_plural': 'Knowledge',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'created_at'], name='memory_know_agent_i_0ce1ab_idx'), models.Index(fields=['mimetype'], name='memory_know_mimetyp_d26bc4_idx'), models.Index(fields=['normalized_name'], name='memory_know_normali_972431_idx')],
            },
        ),
        migrations.CreateModel(
            name='SlidesRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('editorjs', models.JSONField(blank=True, default=dict)),
                ('updated_by', models.CharField(blank=True, default='', max_length=64)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_revisions', to='memory.session')),
                ('slides', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_revisions', to='memory.slides')),
            ],
            options={
                'ordering': ['-version', '-created_at'],
                'indexes': [models.Index(fields=['session', 'version'], name='memory_slid_session_410b0f_idx')],
                'unique_together': {('session', 'version')},
            },
        ),
    ]
