# Generated by Django 5.2.5 on 2025-11-09 13:09

import django.core.validators
import memory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0004_remove_slides_previous_editorjs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='original_name',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='file_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='file',
            field=models.FileField(max_length=500, upload_to=memory.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'doc', 'docx', 'json', 'pdf', 'tsv', 'txt', 'xls', 'xlsm', 'xlsx'])]),
        ),
    ]
