# Generated by Django 5.2.5 on 2025-11-11 10:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import memory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0005_remove_knowledge_original_name_knowledge_file_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(max_length=500, upload_to=memory.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'doc', 'docx', 'json', 'pdf', 'tsv', 'txt', 'xls', 'xlsm', 'xlsx'])])),
                ('content', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('index_status', models.CharField(choices=[('unindexed', 'Unindexed'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='unindexed', max_length=16)),
                ('search_terms', models.JSONField(blank=True, default=list)),
                ('normalized_name', models.CharField(blank=True, db_index=True, default='', max_length=300)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='slides',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='slidesrevision',
            name='memory_slid_session_410b0f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='slidesrevision',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='emotion',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chat',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chat',
            name='response',
            field=models.TextField(blank=True, default='', help_text='Assistant reply text/markdown.'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='viseme',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='session',
            name='thread_id',
            field=models.CharField(db_index=True, default=memory.models.generate_thread_id, help_text='Stable external-facing conversation identifier.', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message="thread_id must be 4–100 chars of lowercase letters, digits, '_' or '-'.", regex='^[a-z0-9_][a-z0-9_\\-]{3,99}$')]),
        ),
        migrations.AlterField(
            model_name='slides',
            name='editorjs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='slides',
            name='updated_by',
            field=models.CharField(blank=True, default='user', max_length=64),
        ),
        migrations.AlterField(
            model_name='slides',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slidesrevision',
            name='slides',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='memory.slides'),
        ),
        migrations.AddConstraint(
            model_name='slides',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 0)), name='slides_version_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='slidesrevision',
            constraint=models.UniqueConstraint(fields=('session', 'version'), name='unique_slide_version_per_session'),
        ),
        migrations.AddField(
            model_name='document',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='memory.session'),
        ),
        migrations.DeleteModel(
            name='Knowledge',
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['session', 'created_at'], name='memory_docu_session_cb6bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['normalized_name'], name='memory_docu_normali_313626_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['sha256'], name='memory_docu_sha256_fc0863_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['session', 'normalized_name'], name='memory_docu_session_126a6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('sha256', ''), _negated=True), fields=('session', 'sha256'), name='unique_document_hash_per_session'),
        ),
    ]
