# Generated by Django 5.2.5 on 2025-10-29 08:36

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Config name (e.g. default-openai).', max_length=100, unique=True)),
                ('llm_service', models.CharField(choices=[('gtts', 'gTTS'), ('elevenlabs', 'ElevenLabs'), ('openai', 'OpenAI'), ('google', 'Google')], default='openai', help_text='Provider for chat completions (e.g., openai, google).', max_length=50)),
                ('text_model', models.CharField(choices=[('gpt-4o', 'GPT-4o (128k)'), ('gpt-4o-mini', 'GPT-4o Mini (64k)'), ('gpt-4o-turbo', 'GPT-4o Turbo (128k)')], default='gpt-4o-mini', max_length=100)),
                ('embed_model', models.CharField(choices=[('text-embedding-3-large', 'Text Embedding 3 Large (16k)'), ('text-embedding-3-small', 'Text Embedding 3 Small (8k)')], default='text-embedding-3-small', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('token_limit', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('context_limit', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('history_limit', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('embed_limit', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'LLM Config',
                'verbose_name_plural': 'LLM Configs',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['is_active', 'updated_at'], name='core_llmcon_is_acti_8fbe7c_idx')],
            },
        ),
    ]
