# Generated by Django 5.2.5 on 2025-11-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='llm_service',
            field=models.CharField(choices=[('gtts', 'gTTS'), ('elevenlabs', 'ElevenLabs'), ('openai', 'OpenAI')], default='openai', help_text='Provider for chat completions (e.g., openai, google).', max_length=50),
        ),
    ]
